Error: USE_AFTER_FREE gutenprint-5.2.6/src/main/mxml-file.c:939: freed_arg: "mxml_add_char" frees "name". gutenprint-5.2.6/src/main/mxml-file.c:326: freed_arg: "free" frees parameter "*buffer". gutenprint-5.2.6/src/main/mxml-file.c:941: double_free: Calling "free" frees pointer "name" which has already been freed.
Error: USE_AFTER_FREE
gutenprint-5.2.6/src/main/mxml-file.c:968: alias: Assigning: "ptr" = "value". Now both point to the same storage.
gutenprint-5.2.6/src/main/mxml-file.c:973: freed_arg: "mxml_add_char" frees "value".
gutenprint-5.2.6/src/main/mxml-file.c:326: freed_arg: "free" frees parameter "*buffer".
gutenprint-5.2.6/src/main/mxml-file.c:976: double_free: Calling "free" frees pointer "value" which has already been freed.

Error: USE_AFTER_FREE
gutenprint-5.2.6/src/main/mxml-file.c:760: freed_arg: "mxml_add_char" frees "buffer".
gutenprint-5.2.6/src/main/mxml-file.c:326: freed_arg: "free" frees parameter "*buffer".
gutenprint-5.2.6/src/main/mxml-file.c:762: double_free: Calling "free" frees pointer "buffer" which has already been freed.